library(Seurat)
library(SCP)
data<-Read10X(data.dir = 'GSE150825/')
sce<-CreateSeuratObject(counts = data,min.cells = 3,min.features = 200)
sce<-HAR_rm_batch(sce,'orig.ident')
library(stringr)
sce$Group<-rownames(sce@meta.data)
sce$Group<-substr(sce$Group,15,20)
sce$Group<-substr(sce$Group,4,10)
sce$orig.ident<-sce$Group
sce$Group<-str_replace(sce$Group,'11|12|13','HC')
sce$Group<-str_replace(sce$Group,'10|14','NPC')
sce$Group<-str_replace(sce$Group,'0|1|2|3|4|5|6|7|8|9|10','NPC')

DotPlot(sce,features = c('ICOSLG'),assay = 'RNA')
CellStatPlot(sce,group.by = 'celltype',stat.by = 'Group')
save(sce,file = 'sce-GSE150825.RData')

load(file = 'sce_GSE150825.RData')
DotPlot(sce,features = 'DCN',assay = 'RNA')
DimPlot(sce,label = T,group.by = 'Group')
library(stringr)
sce$celltype<-sce$seurat_clusters
sce$celltype<-str_replace(sce$celltype,'15','Tumor cells')
sce$celltype<-str_replace(sce$celltype,'20','Epithelial cells')
sce$celltype<-str_replace(sce$celltype,'18|19','Stromal cells')
sce$celltype<-str_replace(sce$celltype,'14|17|22','B')
sce$celltype<-str_replace(sce$celltype,'10|12','Plasma')
sce$celltype<-str_replace(sce$celltype,'11|14|16','T/NK')
sce$celltype<-str_replace(sce$celltype,'13','pDC')
#sce$celltype<-str_replace(sce$celltype,'','DC')
sce$celltype<-str_replace(sce$celltype,'21','Macrophage/DC')
DimPlot(sce,label = T,group.by = 'celltype')
sce$celltype<-str_replace(sce$celltype,'','Tumor cells')
sce$celltype<-str_replace(sce$celltype,'','Epithelial cells')
sce$celltype<-str_replace(sce$celltype,'','Stromal cells')
sce$celltype<-str_replace(sce$celltype,'0|2|6','B')
sce$celltype<-str_replace(sce$celltype,'','Plasma')
sce$celltype<-str_replace(sce$celltype,'1|3|4|5|7|8','T/NK')
sce$celltype<-str_replace(sce$celltype,'','pDC')
sce$celltype<-str_replace(sce$celltype,'','DC')
sce$celltype<-str_replace(sce$celltype,'9','Macrophage/DC')
DimPlot(sce,group.by = 'celltype',label = T)
DotPlot(sce,features = 'ICOSLG',group.by = 'celltype')

save(sce,file = 'sce_GSE150825.RData')
